# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	
	config.vm.provider :libvirt do |libvirt|
		libvirt.default_prefix = "vagrant-ada-";
		libvirt.driver         = "kvm";
		libvirt.cpus           = 1;
		libvirt.memory         = 1024;
	end
	
	config.vm.box = "debian/buster64";
	config.vm.synced_folder ".", "/vagrant", disabled: true;
	config.vm.provision "shell", privileged: true, inline: <<-end
		export DEBIAN_FRONTEND=noninteractive &&\
		apt-get -y update &&\
		apt-get -y upgrade &&\
		apt-get -y dist-upgrade;
	end
	
	config.vm.define "dev", primary: true do |config|
		config.vm.hostname = "ada-dev";
		config.vm.synced_folder "..", "/home/vagrant/ada", type: :sshfs;
		config.vm.provision "shell", inline: <<-end
			export DEBIAN_FRONTEND=noninteractive &&\
			apt-get -y install python3 python3-pip &&\
			python3 -m pip install --system ansible;
		end
	end
	
	config.vm.define "test" do |config|
		config.vm.hostname = "ada-test";
	end
end

