# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
    libvirt.default_prefix = "vagrant-ada-"
    libvirt.driver = "kvm"
    libvirt.cpus = 1
    libvirt.memory = 1024
  end

  config.vm.box = "debian/buster64"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "shell", privileged: true, inline: <<-END
    export DEBIAN_FRONTEND=noninteractive &&
    apt-get -y update &&
    apt-get -y upgrade &&
    apt-get -y dist-upgrade
  END

  config.vm.define "dev", primary: true do |dev_config|
    dev_config.vm.hostname = "ada-dev"
    dev_config.vm.synced_folder "..", "/home/vagrant/ada", type: :sshfs

    dev_config.vm.provision "shell", inline: <<-END
      export DEBIAN_FRONTEND=noninteractive &&
      apt-get -y install python3 python3-pip &&
      python3 -m pip install --system ansible
    END
  end

  config.vm.define "test" do |test_config|
    test_config.vm.hostname = "ada-test"
  end
end
